# Generated by Django 5.2.1 on 2025-05-26 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=70, null=True)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=70)),
                ('zip_code', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('STUDIO', 'Studio'), ('ROOM', 'Room'), ('LOFT', 'Loft'), ('PENTHOUSE', 'Penthouse'), ('BUNGALOW', 'Bungalow'), ('VILLA', 'Villa'), ('TINY_HOUSE', 'Tiny House'), ('MOBILE_HOME', 'Mobile Home')], default='Apartment', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-rating', 'created_at'],
            },
        ),
    ]
