# Generated by Django 5.2.1 on 2025-05-31 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyviewhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyviewhistory',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='properties.property'),
        ),
    ]
