# Generated by Django 5.2.1 on 2025-06-01 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_deleted_at_property_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='property',
            new_name='rent_property',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='rent_property_type',
        ),
        migrations.RenameField(
            model_name='propertyviewhistory',
            old_name='property',
            new_name='rent_property',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='property',
            new_name='rent_property',
        ),
        migrations.AlterUniqueTogether(
            name='propertyviewhistory',
            unique_together={('user', 'rent_property')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('rent_property', 'author')},
        ),
    ]
