# Generated by Django 5.2.1 on 2025-06-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_address_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=6),
        ),
    ]
