# Generated by Django 5.2.1 on 2025-05-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord')], default='Tenant', max_length=40),
        ),
    ]
